services:
  task-manager-db:
    image: postgres:17.2
    container_name: task-manager-db
    environment:
      POSTGRES_DB: task_manager_db
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password123"
    ports:
      - "5435:5432"
    volumes:
      - task_manager_db_data:/var/lib/postgresql/data

    restart: always
    networks:
      - task_manager_network

  task-manager-redis:
    image: bitnami/redis:6.2
    container_name: task-manager-redis
    restart: always
    ports:
      - '6385:6379'
    command: redis-server --loglevel warning --protected-mode no
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - task-manager-redis-data:/data

  task-manager-test-db:
    image: postgres:17.2
    container_name: task-manager-test-db
    environment:
      POSTGRES_DB: task_manager_test_db
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password123"
    ports:
      - "5436:5432"
    volumes:
      - task_manager_test_db_data:/var/lib/postgresql/data
    networks:
      - task_manager_network

volumes:
  task_manager_db_data:
  task-manager-redis-data:
  task_manager_test_db_data:

networks:
  task_manager_network:
    driver: bridge
